apiVersion: apps/v1
kind: Deployment
metadata:
  name: geography
  labels:
    app: geography
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geography
  template:
    metadata:
      labels:
        app: geography
    spec:
      containers:
        - name: geography
          image: domedev7/dome-dev:geography  # my custom local registry
          imagePullPolicy: Always  # dont forget its needed for reset or same image in cache will be used!
          ports:
            - containerPort: 3000 # expressJS port from npm start script
---
apiVersion: v1
kind: Service
metadata:
  name: geography
spec:
  type: NodePort
  selector:
    app: geography
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30939
---
